[build-system]
requires = ["setuptools>=77.0"]

build-backend = "setuptools.build_meta"

[project]
name = "seisio"

license = "LGPL-3.0-or-later"

license-files = ["LICEN[CS]E*"]

dynamic = ["version"]

authors = [
  { name="Thomas Hertweck", email="geophysics@email.de" },
]

maintainers = [
  { name="Thomas Hertweck", email="geophysics@email.de" },
]

description = "I/O of seismic data"

readme = "README.md"

requires-python = ">=3.10"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
  "numpy",
  "pandas",
  "numba",
  "fsspec",
]

keywords = [
  "seismic",
  "SU",
  "SEGY", "SEG-Y",
  "SEG2",
  "I/O",
  "read",
  "write",
  "radar", "GPR",
  "geophysics",
]

[project.urls]
Repository = "https://gitlab.kit.edu/thomas.hertweck/seisio"

[project.optional-dependencies]
opt = [
  "tabulate",
]
test = [
  "pytest>=7.0",
]

[tool.setuptools.packages.find]
include = ["seisio*"]
exclude = ["docs*", "examples*", "tests*"]

[tool.setuptools.dynamic]
version = { attr = "seisio.__version__" }

[tool.setuptools.package-data]
"seisio.json" = ["*.json"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
]
